### ISSUE TITLE
Storage is not persistent after closing the app

### ISSUE THREAD

**Issue by tranjustin** [TheCocoaProject/cordova-plugin-nativestorage#37] opened 2016-08-31 17:57 UTC
After I close the app down and re-open the app, the storage info is no longer existed.  I am currently testing on ios 9.3.3 and android 6.0.1.

**Comment by alokrajiv** [comment] 2016-08-31 21:03
Highly unlikely because in Android we use SharedPreference which is exactly for preventing this issue from occurring. It should work in all versions of Android uniformly as well.

Pls add your code so that we can replicate the issue. Run the demo and see if you still face the same issue.

**Comment by seeya** [comment] 2016-09-08 11:28
I encountered this problem too. The problem for me was I kept clearing my cache with `window.cache.clear(null, null ); window.cache.cleartemp();` every time the application starts. After removing that 2 lines of codes it worked perfectly.

**Comment by alokrajiv** [comment] 2016-09-08 15:40
ohk...so you must be falling back to localstorage? because theoretically nativestorage will not be affected by the window object.

**Comment by PierBover** [comment] 2016-09-27 15:54
@alokrajiv is there a way to know when the fallback to localstorage happens?

I'm getting numerous reports of users randomly losing their data.

**Comment by GillesC** [comment] 2016-09-27 15:56
@PierBover The following code is used to check if the application is running in the browser (i.e. initiating localstorage fallback):

```
function isInBrowser() {
  inBrowser = (window.cordova && window.cordova.platformId === 'browser') || !(window.phonegap || window.cordova);
  return inBrowser;
}
```

**Comment by PierBover** [comment] 2016-09-27 15:57
But, in principle if it's running in Android or iOS localStorage would never be used, right?

**Comment by GillesC** [comment] 2016-09-27 15:57
@PierBover that should be indeed the case :)

**Comment by PierBover** [comment] 2016-09-27 15:58
Thanks, I'm trying to figure out what is going on with my users. I'll report any bugs if any...

**Comment by kristfal** [comment] 2016-10-04 09:11
I am also experiencing random data losses on app restarts. It is probably a race condition issue as it occurs randomly on app restarts with the -js code staying the same on my end. The issue seems to be isolated to iOS on my situation.

My findings so far are:

Calling NativeStorage.getItem in the same app session when I've lost data does not return any callbacks. 

Eg:

`NativeStorage.getItem("reference", function(e){console.log(e)}, function(e){console.log(e)});
`

Would not return any CBs. Omitting the error handler would return an error, so the plugin does indeed load. Reloading the webview `location.reload()` does not resolve the issue, but restarting the application does resolve this issue.

I'll keep digging.

**Comment by danielcrk-cn** [comment] 2016-10-26 13:12
Guys, i've just discovered a really dumb misstake I was doing that caused my app to "lose data".

My data loading function was happening outside the platform.ready() event. Now, by pure luck, the plugin was loaded in time most of app launches, but sometimes, the data loading attempt was executed before the plugins were loaded and the app ended up with no data.

So for the end user, this obviously ment "data is sometimes lost", tho the real issue was of course "data was sometimes not being able to load".

Hope this helps someone!

**Comment by alokrajiv** [comment] 2016-10-26 13:20
@danielcrk-cn So now you are not facing any issues, correct? Because it is strange that in 2months we haven't figured the problem? Are others still facing the issue?

**Comment by GillesC** [comment] 2016-10-26 13:21
I'm closing this issue because the fault (probably) lies with the plugin-user.

**Closed by GillesC** 2016-10-26 13:21 UTC
Labels: bug

**Comment by danielcrk-cn** [comment] 2016-10-26 13:22
@alokrajiv I've just made the fix so I'll have to give it a few days, but I'm quite sure that this was the root cause of the problem - it makes perfect sense.

If I notice this issue again despite the fix, I'll open a new issue here.

Thanks for this great plugin!

**Comment by alokrajiv** [comment] 2016-10-26 13:24
@danielcrk-cn Fantastic!! Don't open another issue though, just comment and we'll reopen this one. If someone else still faces the issue, please comment.

**Comment by KimGames** [comment] 2018-05-28 11:40
I still have the same problem, some solution? My problem is: at first time, I'd like to read a QR Code and save it with NativeStorage. After closing the app, I don't want to read the QR Code again. So, the page Intro(the page that allows me to read the QR Code) should not open. My code for save data in IntroPage is `private save(val){
    console.log('data added ' + val);
    this.nativeStorage.setItem(STORAGE_KEY, {property: val})
      .then(
        () => console.log('Stored item!'),
        error => this.makeToastMessage('Error storing item', '5000', 'center')
      );
  };`
and my code for get data in `app.component.ts` is `let localStorage:string = "Not got";
    this.nativeStorage.getItem(STORAGE_KEY)
      .then(
        item => localStorage = item.properity,
        error => console.log("Error getting item. Error: " + error)
      );`

**Comment by puneethshetty12** [comment] 2018-07-02 12:33
I am facing the same issue. The app loses data after I close it.

**Comment by suhail339** [comment] 2019-03-13 08:00
I am facing the ame issue on ios, is there anything i missed? Currently using > 2.3
